#!/bin/bash
set -e

readme () {

open -a /Applications/Safari.app http://randymcmillan.github.com/cdv-ios-plugin-templates/

}

help () {
    cat<<EOF

    Usage: quick-vim [install|uninstall|upgrade|help|readme]

    Commands:

    $ ./installer install

    install    populates submodules and creates a symlink to the Xcode File
    Templates Folder

    $ ./installer uninstall

    uninstall  removes synlinks from Xcode File Templates Folder

    $ ./installer ungrade

    upgrade    clobbers existing setup and installs fresh from git

    $ ./installer help

    help       print this msg

    $ ./installer readme

    readme     opens http://randymcmillan.github.com/cdv-ios-plugin-templates/
    in Safari.app

    NOTE       If you forked this repo I recommend understanding 
    submodules.

EOF

}

# copy in pathogen and then clone in bundles
install () {

    git submodule init
    git submodule update --init --recursive

    ls > bundles.txt

    bundles=$(cat ./bundles.txt)

    for template in $bundles; do
   
        if [ -e ~/Library/Developer/Xcode/Templates/File\ Templates/$template ]
        then
        echo  '~/Library/Developer/Xcode/Templates/File\ Templates/'$template' already exists'
        else
        echo  'Symlinking '$template
        ln -s $PWD/$template ~/Library/Developer/Xcode/Templates/File\ Templates/$template
        fi

    done
}

# if backup exists clobbers home vim and copies in backup
uninstall () {

    ls > bundles.txt

    bundles=$(cat ./bundles.txt)

    for template in $bundles; do
   
        if [ -e ~/Library/Developer/Xcode/Templates/File\ Templates/$template ]
        then
        
        rm ~/Library/Developer/Xcode/Templates/File\ Templates/$template
        echo  'removing symlink to ~/Library/Developer/Xcode/Templates/File\ Templates/'$template'! '

        fi

    done
    
}

# Removes symlinks, pulls latest from git, installs it
upgrade () {
    uninstall
    git pull
    install
}

# bash test for a valid arg and execute it if so; otherwise show the help
if [ "$1" != "" ]; then
    wl=(install uninstall upgrade readme help)
    for i in "${wl[@]}"
    do
        if [ "$i" == "$1" ]
        then
            $1
            exit 0
        fi
    done
fi

# show some help
help
exit 0


#
#  ___FILEBASENAME___
#  CDVEmailComposer Template Created Jan 7 2013
#  Copyright 2013 @RandyMcMillan
